/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:tensorflow:From /Library/Python/3.9/site-packages/tensorflow/python/util/dispatch.py:1260: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2024-08-01 16:37:54.749062: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
WARNING:tensorflow:From /Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s44124668_context.py:72: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:`tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
Traceback (most recent call last):
  File "/Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s44124668_context.py", line 86, in <module>
    main()
  File "/Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s44124668_context.py", line 75, in main
    train_step.run(feed_dict={x: image_batch, y: label_batch, keep_prob: 0.5})
  File "/Library/Python/3.9/site-packages/tensorflow/python/framework/ops.py", line 1631, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/Library/Python/3.9/site-packages/tensorflow/python/framework/ops.py", line 4539, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/Library/Python/3.9/site-packages/tensorflow/python/client/session.py", line 972, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Library/Python/3.9/site-packages/tensorflow/python/client/session.py", line 1189, in _run
    raise ValueError(
ValueError: Cannot feed value of shape (50,) for Tensor Placeholder_1:0, which has shape (None, 10)
