/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2024-08-01 16:52:47.033636: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
Traceback (most recent call last):
  File "/Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s55237206_context.py", line 40, in <module>
    sess.run(train_step, feed_dict=train_data)
  File "/Library/Python/3.9/site-packages/tensorflow/python/client/session.py", line 972, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Library/Python/3.9/site-packages/tensorflow/python/client/session.py", line 1189, in _run
    raise ValueError(
ValueError: Cannot feed value of shape (100, 100, 3) for Tensor Placeholder:0, which has shape (1, 100, 100, 3)
