/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s57917398_context.py", line 7, in <module>
    intersection = tf.sets.intersection(tf.convert_to_tensor(idx1), tf.convert_to_tensor(idx2))
  File "/Library/Python/3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Library/Python/3.9/site-packages/tensorflow/python/framework/ops.py", line 1021, in _create_c_op
    raise ValueError(e.message)
ValueError: Shape must be at least rank 2 but is rank 1 for '{{node DenseToDenseSetOperation}} = DenseToDenseSetOperation[T=DT_INT32, set_operation="intersection", validate_indices=true](Const, Const_1)' with input shapes: [3], [3].
