/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s58644645_context.py", line 48, in <module>
    run()
  File "/Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s58644645_context.py", line 38, in run
    train_images, train_labels, test_images, test_labels = load_dataset()
  File "/Users/usi/Documents/RealBugsAnalysis/sfdata/runs/s58644645_context.py", line 10, in load_dataset
    test_images = test_images.reshape((60000, 28 * 28))
ValueError: cannot reshape array of size 7840000 into shape (60000,784)
